const project3 = [
    {
      id: 1,
      title: "",
      image: "",
      deployed: "",
      repo: "",
      // description: '',
      team_members: "",
    },
    {
      id: 2,
      title: "",
      image: "",
      deployed: "",
      repo: "",
      // description: '',
      team_members: "",
    },
    {
      id: 3,
      title: "",
      image: "",
      deployed: "",
      repo: "",
      // description: '',
      team_members: "",
    },
    {
    id: 4,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 5,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 6,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 7,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 8,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 9,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    }, {
    id: 10,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 11,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 12,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    },
    {
    id: 13,
    title: "",
    image: "",
    deployed: "",
    repo: "",
    // description: '',
    team_members: "",
    }
  ];
  
  export default project3;
  