const project2 = [{
        id: 1,
        title: '',
        // image: ,
        deployed: '',
        repo: 'https://github.com/MichaelSinn/game-hosting-site',
        // description: '',
        team_members: "Michael S., Matuesz",
    },
    {
        id: 2,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Harmonjot, Alastair, Sash",
    },
    {
        id: 3,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Shayne, Constan, Nathan",
    },
    {
        id: 4,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Minh, Dylan, Diana",
    },
    {
        id: 5,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Trishane, Esra, Abed",
    },
    {
        id: 6,
        title: '',
        // image: ,
        deployed: '',
        repo: 'https://github.com/Favour01216/Adoption-site',
        // description: '',
        team_members: "Sagiri, Ellison, Favour",
    },
    {
        id: 7,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Salman, Amy, Jordan",
    },
    {
        id: 8,
        title: '',
        // image: ,
        deployed: '',
        repo: 'https://github.com/Iva416/yourStore',
        // description: '',
        team_members: "Ben, Jaymen, Iva",
    },
    {
        id: 9,
        title: '',
        // image: ,
        deployed: '',
        repo: 'https://github.com/thivsiv28/Team9',
        // description: '',
        team_members: "Thiviya, Hongdong, Muaiz",
    },
    {
        id: 10,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Kaye, Nick, Hao",
    },
    {
        id: 11,
        title: '',
        // image: ,
        deployed: '',
        repo: 'https://github.com/ramosw1993/Get-A-Job',
        // description: '',
        team_members: "William, Pak, Hannah",
    },
    {
        id: 12,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Safa, Alex, Gabriella",
    },
    {
        id: 13,
        title: '',
        // image: ,
        deployed: '',
        repo: '',
        // description: '',
        team_members: "Xin, Keyshawn, Abdirahman",
    },



];

export default project2;