const project2 = [{
        id: 1,
        title: 'Game Hosting Site',
        image: './images/project2/gamehostingsite.png',
        deployed: 'https://game-hosting-site.herokuapp.com/',
        repo: 'https://github.com/MichaelSinn/game-hosting-site',
        // description: '',
        team_members: "Michael S., Matuesz",
    },
    {
        id: 2,
        title: 'The Lending Station',
        // image: './images/project2/',
        deployed: 'https://the-lending-station.herokuapp.com/',
        repo: 'https://github.com/sashdc/the-lending-station',
        // description: '',
        team_members: "Harmonjot, Alastair, Sash",
    },
    {
        id: 3,
        title: 'Psychic Journey',
        image: './images/project2/psychicjourney.png',
        deployed: 'https://psychic-journey.herokuapp.com/',
        repo: 'https://github.com/NathanKryz/psychic-journey.git',
        // description: '',
        team_members: "Shayne, Constan, Nathan",
    },
    {
        id: 4,
        title: 'Goodie Foodie Reviews',
        image: './images/project2/goodiefoodie.png',
        deployed: 'https://goodie-foodies-heroku.herokuapp.com/',
        repo: 'https://github.com/DianasJourney/GoodieFoodieReviews',
        // description: '',
        team_members: "Minh, Dylan, Diana",
    },
    {
        id: 5,
        title: 'Tea Gram',
        image: './images/project2/teagram.png',
        deployed: 'https://tea-gram.herokuapp.com/',
        repo: 'https://github.com/EsraWameed/teagram',
        // description: '',
        team_members: "Trishane, Esra, Abed",
    },
    {
        id: 6,
        title: 'Pet Place',
        // image: './images/project2/',
        deployed: 'https://adoption-website.herokuapp.com/',
        repo: 'https://github.com/Favour01216/Adoption-site',
        // description: '',
        team_members: "Sagiri, Ellison, Favour",
    },
    {
        id: 7,
        title: 'Budget',
        image: './images/project2/budget.png',
        deployed: 'https://bloodcurdling-vampire-96793.herokuapp.com/',
        repo: 'https://github.com/jwiz9/verbose-robot',
        // description: '',
        team_members: "Salman, Amy, Jordan",
    },
    {
        id: 8,
        title: 'Your Store',
        image: './images/project2/yourstore.png',
        deployed: 'https://your-store-jibstudios.herokuapp.com/',
        repo: 'https://github.com/Iva416/yourStore',
        // description: '',
        team_members: "Ben, Jaymen, Iva",
    },
    {
        id: 9,
        title: 'Shophub',
        image: './images/project2/shophub.png',
        deployed: 'https://frightful-coffin-45274.herokuapp.com/',
        repo: 'https://github.com/thivsiv28/Team9',
        // description: '',
        team_members: "Thiviya, Hongdong, Muaiz",
    },
    {
        id: 10,
        title: 'Ratatoullie',
        // image: './images/project2/',
        deployed: '',
        repo: 'https://github.com/pav1593/Ratatouille',
        // description: '',
        team_members: "Kaye, Nick, Hao",
    },
    {
        id: 11,
        title: 'Get A Job',
        image: './images/project2/getajob.png',
        deployed: 'https://get-a-job.herokuapp.com/',
        repo: 'https://github.com/ramosw1993/Get-A-Job',
        // description: '',
        team_members: "William, Pak, Hannah",
    },
    {
        id: 12,
        title: 'Tech Event Planner',
        // image: './images/project2/',
        deployed: 'https://tech-event-planner.herokuapp.com/',
        repo: 'https://github.com/hmhtom/tech-event-planner',
        // description: '',
        team_members: "Safa, Alex, Gabriella",
    },
    {
        id: 13,
        title: 'Food City Grocery',
        image: './images/project2/foodcitygrocery.png',
        deployed: 'https://food-city-grocery.herokuapp.com/',
        repo: 'https://github.com/keysbhag/Food-City-Grocery',
        // description: '',
        team_members: "Xin, Keyshawn, Abdirahman",
    },



];

export default project2;