const project1 = [{
        id: 1,
        title: 'Wordplay',
        // image: wordplay,
        deployed: 'https://amywilford.github.io/Word-Play/index.html',
        repo: 'https://github.com/AmyWilford/Word-Play',
        // description: '',
        team_members: "Amy, Sash, Kaye",
    }, {
        id: 2,
        title: 'Where 2 Watch',
        // image: where2watch,
        deployed: 'https://dylangodfrey.github.io/Where2Watch/',
        repo: 'https://github.com/DylanGodfrey/Where2Watch',
        // description: "",
        team_members: "Dylan, Favour, Michael N.",
    },
    {
        id: 3,
        title: 'Beer Meal Buddies',
        // image: beermeal,
        deployed: 'https://branbao1995.github.io/Beer-Meal-Buddies/',
        repo: 'https://github.com/BranBao1995/Beer-Meal-Buddies',
        // description: "",
        team_members: "Hongdong, Matuesz, Diana",
    },
    {
        id: 4,
        title: 'Camping Journal',
        // image: campingjournal,
        deployed: 'https://michaelsinn.github.io/camping-journal/',
        repo: 'https://github.com/MichaelSinn/camping-journal',
        // description: '',
        team_members: "Michael S., Trishane, Imanuel",
    },
    {
        id: 5,
        title: 'Flight Planner',
        // image: flightplanner,
        deployed: 'https://benliu104.github.io/Project01-FlightPlanner/',
        repo: 'https://github.com/BenLiu104/Project01-FlightPlanner',
        // description: '',
        team_members: "Ben, Harmonjot, Minh",
    },
    {
        id: 6,
        title: 'Your Movie Database',
        // image: ymdb,
        deployed: 'https://hmhtom.github.io/Your-Movie-Databse/',
        repo: 'https://github.com/hmhtom/Your-Movie-Databse',
        // description: '',
        team_members: "Abdiriman, Thiviya, Alex",
    },
    {
        id: 7,
        title: 'Learning My Way',
        // image: learningmyway,
        deployed: 'https://abedhasan79.github.io/Learning-My-Way/',
        repo: 'https://github.com/abedhasan79/Learning-My-Way',
        // description: '',
        team_members: "Abed, Hannah, Safa",
    },
    {
        id: 8,
        title: 'FindFlix',
        // image: findflix,
        deployed: 'https://keysbhag.github.io/FindFlix-Project/',
        repo: 'https://github.com/keysbhag/FindFlix-Project',
        // description: "",
        team_members: "Keyshawn, Pak, Rajvir",
    },
    {
        id: 9,
        title: 'Motivation Locale',
        // image: motivation,
        deployed: 'https://esrawameed.github.io/Motivation-Locale/',
        repo: 'https://github.com/EsraWameed/Motivation-Locale',
        // description: "",
        team_members: "Esra, Nathan, Salman",
    },
    {
        id: 10,
        title: 'Search Displayer',
        // image: searchdisplayer,
        deployed: 'https://muaizkh.github.io/Search-Displayer/',
        repo: 'https://github.com/Muaizkh/Search-Displayer',
        // description: '',
        team_members: "Jaymen, Gabriella, Muaiz",
    },
    {
        id: 11,
        title: 'Check Your Move',
        // image: checkyourmovie,
        deployed: 'https://roflmelon.github.io/movie-db-app/',
        repo: 'https://github.com/roflmelon/movie-db-app',
        // description: '',
        team_members: "Shayne, Hao, Xin",
    },
    {
        id: 12,
        title: 'News Headlines Aggregator',
        // image: newsheadline,
        deployed: 'https://honsumal.github.io/news-headline-aggregator/',
        repo: 'https://github.com/Honsumal/news-headline-aggregator',
        // description: '',
        team_members: "Nick, Ellison, Alastair",
    },
    {
        id: 13,
        title: 'Music Hub',
        // image: musichub,
        deployed: 'https://iva416.github.io/MusicHub/',
        repo: 'https://github.com/Iva416/MusicHub',
        // description: '',
        team_members: "Iva, Will, Constan",
    },
    {
        id: 14,
        title: 'Whats The Word?',
        // image: whatstheword,
        deployed: 'https://sagirikenaga.github.io/whats-the-word/',
        repo: 'https://github.com/sagirikenaga/whats-the-word',
        // description: '',
        team_members: "Jordan, Sagiri",
    },

];

export default project1;